/-
  DumpProgMain — emit the LowIR-compiled library for the bare-metal QEMU
  smoke test (bare/shellmain.s):

    bare/progmain.bin       the compiled bytes of `compileProg libEnv "main"`
    bare/progmain.inc       .equ MAIN_OFF, <byte offset of `main` in the blob>
    bare/progmain.syms      objcopy --add-symbol directives for the function
                            table (used by `make dismain` to label the blob)
    bare/progmain.expected  the 8 observables the shim should print
                            (16 uppercase hex digits per line), computed by
                            running `main` on the IL semantics

  Run from `lean/`:  lake env lean --run DumpProgMain.lean
  (Not part of any lib target — a tool, not a module.)
-/
import LowIR.ProgLib
import LowIR.Compile

open LowIR.Compile LowIR.Prog.Lib

def hex16 (w : BitVec 64) : String :=
  String.ofList <| (List.range 16).reverse.map fun i =>
    let nib := (w.toNat >>> (4 * i)) % 16
    Char.ofNat (if nib < 10 then 48 + nib else 55 + nib)

def main : IO Unit := do
  let some (instrs, ftab, dtab) := compileProgT libProgram "cmain"
    | throw (IO.userError "compileProgT libProgram cmain failed")
  let some blob := progBytes libProgram "cmain"
    | throw (IO.userError "progBytes failed")
  let some mainOff := ftab.lookup "cmain"
    | throw (IO.userError "no `cmain` in the function table")
  IO.FS.writeBinFile "../bare/progmain.bin"
    (ByteArray.mk (blob.map (fun b => b.toNat.toUInt8)).toArray)
  IO.FS.writeFile "../bare/progmain.inc"
    s!"# generated by lean/DumpProgMain.lean — byte offset of the entry fn in progmain.bin\n.equ MAIN_OFF, {mainOff}\n"
  let fsyms := ("entry_stub", 0) :: ("halt_pad", 4) :: ftab
  IO.FS.writeFile "../bare/progmain.syms"
    (String.join (fsyms.map (fun nf =>
       s!"--add-symbol {nf.1}=.text:{nf.2},function,global\n")
     ++ dtab.map (fun nd =>
       s!"--add-symbol {nd.1}=.text:{nd.2},object,global\n")))
  let some s := LowIR.Prog.run libProgram 0 200000 "cmain" [] (fun _ => 0) SP0
    | throw (IO.userError "IL run of cmain failed")
  let outs := cmainF.rets.toList.map s.rget
  IO.FS.writeFile "../bare/progmain.expected"
    (String.join (outs.map (fun w => hex16 w ++ "\n")))
  IO.println s!"progmain.bin: {blob.length} bytes ({instrs.length} instrs + data), entry cmain @ {mainOff}"
  IO.println s!"observables: {outs.map (·.toNat)}"
  IO.println s!"fn table: {ftab}"
  IO.println s!"data table: {dtab}"
