/-
  DumpProgMain — emit the LowIR-compiled library for the bare-metal QEMU
  smoke test (bare/shellmain.s):

    bare/progmain.bin       the compiled bytes of `compileProg libEnv "main"`
    bare/progmain.inc       .equ MAIN_OFF, <byte offset of `main` in the blob>
    bare/progmain.syms      objcopy --add-symbol directives for the function
                            table (used by `make dismain` to label the blob)
    bare/progmain.expected  the 8 observables the shim should print
                            (16 uppercase hex digits per line), computed by
                            running `main` on the IL semantics

  Run from `lean/`:  lake env lean --run DumpProgMain.lean
  (Not part of any lib target — a tool, not a module.)
-/
import LowIR.ProgLib
import LowIR.Compile

open LowIR.Compile LowIR.Prog.Lib

def hex16 (w : BitVec 64) : String :=
  String.ofList <| (List.range 16).reverse.map fun i =>
    let nib := (w.toNat >>> (4 * i)) % 16
    Char.ofNat (if nib < 10 then 48 + nib else 55 + nib)

def main : IO Unit := do
  let some (instrs, table) := compileProgT libEnv "main"
    | throw (IO.userError "compileProgT libEnv main failed")
  let some mainOff := table.lookup "main"
    | throw (IO.userError "no `main` in the function table")
  let bytes := LowIR.asmBytes instrs
  IO.FS.writeBinFile "../bare/progmain.bin"
    (ByteArray.mk (bytes.map (fun b => b.toNat.toUInt8)).toArray)
  IO.FS.writeFile "../bare/progmain.inc"
    s!"# generated by lean/DumpProgMain.lean — byte offset of `main` in progmain.bin\n.equ MAIN_OFF, {mainOff}\n"
  let syms := ("entry_stub", 0) :: ("halt_pad", 4) :: table
  IO.FS.writeFile "../bare/progmain.syms"
    (String.join (syms.map fun nf =>
      s!"--add-symbol {nf.1}=.text:{nf.2},function,global\n"))
  let some s := LowIR.Prog.run libEnv 0 200000 "main" [] (fun _ => 0) SP0
    | throw (IO.userError "IL run of main failed")
  let outs := mainF.rets.toList.map s.rget
  IO.FS.writeFile "../bare/progmain.expected"
    (String.join (outs.map (fun w => hex16 w ++ "\n")))
  IO.println s!"progmain.bin: {bytes.length} bytes ({instrs.length} instrs), MAIN_OFF = {mainOff}"
  IO.println s!"observables: {outs.map (·.toNat)}"
  IO.println s!"fn table: {table}"
